version: '4'
services:
  db:
    image: "leanbi/madlib_postgres"
    ports:
     - "11000:5432"
    networks:
     gateway:
        aliases:
        - db
     
  nodered:
    image: "leanbi/docker_nodered_gateway_nodered:latest"
    ports:
     - "11001:1880"
    networks:
     gateway:
        aliases:
        - nodered
  
  openscoring:
    image: "jpmml/openscoring"
    ports:
     - "11002:8080"
     
  pgadmin:
    image: "meedan/pgadmin"
    ports: 
     - "11003:5050"
    networks:
     gateway:
        aliases:
        - pgadmin

networks:
  gateway:
#docker rm -f  $(docker ps -a -q -f name=desktop* )